#ifndef TEST_UTILS_HPP
#define TEST_UTILS_HPP

#include <string_view>

constexpr std::string_view graph_gr = "d\n"
                                      "7 24\n"
                                      "0 1 6 0\n"
                                      "1 0 6 0\n"
                                      "0 3 3 0\n"
                                      "3 0 3 0\n"
                                      "0 2 4 0\n"
                                      "2 0 4 0\n"
                                      "1 6 6 0\n"
                                      "6 1 6 0\n"
                                      "3 4 5 0\n"
                                      "4 3 5 0\n"
                                      "3 1 2 0\n"
                                      "1 3 2 0\n"
                                      "3 2 3 0\n"
                                      "2 3 3 0\n"
                                      "2 4 5 0\n"
                                      "4 2 5 0\n"
                                      "3 5 3 0\n"
                                      "5 3 3 0\n"
                                      "4 5 1 0\n"
                                      "5 4 1 0\n"
                                      "4 6 3 0\n"
                                      "6 4 3 0\n"
                                      "5 6 2 0\n"
                                      "6 5 2 0\n";

constexpr std::string_view graph_gr_esx = "d\n"
                                          "7 24\n"
                                          "0 1 6 0\n"
                                          "1 0 6 0\n"
                                          "0 3 3 0\n"
                                          "3 0 3 0\n"
                                          "0 2 4 0\n"
                                          "2 0 4 0\n"
                                          "1 6 6 0\n"
                                          "6 1 6 0\n"
                                          "3 4 5 0\n"
                                          "4 3 5 0\n"
                                          "3 1 2 0\n"
                                          "1 3 2 0\n"
                                          "3 2 3 0\n"
                                          "2 3 3 0\n"
                                          "2 4 5 0\n"
                                          "4 2 5 0\n"
                                          "3 5 3 0\n"
                                          "5 3 3 0\n"
                                          "4 5 1 0\n"
                                          "5 4 1 0\n"
                                          "4 6 2 0\n"
                                          "6 4 2 0\n"
                                          "5 6 2 0\n"
                                          "6 5 2 0\n";

#endif